# Generated by Django 2.2 on 2020-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_auto_20201127_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
