# Generated by Django 3.1.5 on 2021-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('favorite_book', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
